// Regenerate with `cargo test -p jclean-desktop`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  Dev builds only: prints a message from the UI to the terminal (used by
	 *  the frame-rate probe). Does nothing in release builds.
	 */
	devLog: (message: string) => __TAURI_INVOKE<void>("dev_log", { message }),
	setWindowMode: (mode: WindowMode) => typedError<null, string>(__TAURI_INVOKE("set_window_mode", { mode })),
	/**
	 *  Starts a scan on a background thread. Results stream through `on_update`;
	 *  the call returns immediately.
	 */
	startScan: (mode: Mode, onUpdate: Channel<ScanUpdate>) => typedError<null, string>(__TAURI_INVOKE("start_scan", { mode, onUpdate })),
	/**  Stops the running scan; what was found so far is kept. */
	cancelScan: () => __TAURI_INVOKE<void>("cancel_scan"),
	/**  One level of the full scan's folder map. `""` is the top level. */
	mapLevel: (id: string) => typedError<MapCellDto[], string>(__TAURI_INVOKE("map_level", { id })),
	volumeInfo: () => __TAURI_INVOKE<{
	name: string,
	total: number,
	/**  What Finder calls available: includes purgeable space. */
	available: number,
	/**  Space macOS frees on its own when it needs it. */
	purgeable: number,
} | null>("volume_info"),
	/**
	 *  The last completed scan, shown instantly at launch until a fresh one
	 *  finishes (spec §10).
	 */
	cachedScan: () => __TAURI_INVOKE<{
	/**  Unix seconds. */
	savedAt: number,
	items: ItemDto[],
} | null>("cached_scan"),
};

/* Types */
export type AppInfo = {
	version: string,
	coreVersion: string,
	platform: string,
	/**  The user's home folder, for showing paths as `~/…`. */
	home: string,
};

export type CachedScan = {
	/**  Unix seconds. */
	savedAt: number,
	items: ItemDto[],
};

export type CategoryDto = "apps" | "developer" | "system" | "media" | "documents" | "other";

/**
 *  A list item as the UI sees it. Sizes are numbers of bytes (JS numbers are
 *  exact up to 9 PB). `#[specta(type = u32)]` only makes the exported
 *  TypeScript type a plain `number`: these values are never NaN.
 */
export type ItemDto = {
	id: string,
	ruleId: string,
	name: string | null,
	path: string | null,
	bytes: number,
	bytesKnown: boolean,
	lastUsed: number | null,
	risk: RiskDto,
	category: CategoryDto,
	method: MethodDto,
	cleanable: boolean,
	blockedReason: string | null,
	preselected: boolean,
	mayShareBlocks: boolean,
	project: ProjectDto | null,
};

export type MapCellDto = {
	id: string,
	name: string,
	bytes: number,
	category: CategoryDto,
	reclaimable: number,
	itemId: string | null,
	hasChildren: boolean,
	other: boolean,
};

export type MethodDto = "delete" | "trash" | "command" | "none";

export type Mode = "quick" | "full";

export type ProjectDto = {
	name: string,
	root: string,
	active: boolean,
};

export type RiskDto = "safe" | "review" | "caution" | "info";

export type ScanUpdate = { kind: "stage"; label: string } | { kind: "progress"; fraction: number } | { kind: "item"; item: ItemDto } | { kind: "finished"; partial: boolean; notes: string[]; hasTree: boolean };

export type VolumeInfo = {
	name: string,
	total: number,
	/**  What Finder calls available: includes purgeable space. */
	available: number,
	/**  Space macOS frees on its own when it needs it. */
	purgeable: number,
};

export type WindowMode = "compact" | "expanded";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

