import {
  AppWindow,
  Archive,
  Beer,
  Brain,
  Clock,
  Code,
  Compass,
  Container,
  Database,
  Download,
  FileBox,
  FileWarning,
  FolderCog,
  FolderOutput,
  FolderTree,
  Globe,
  Hammer,
  HardDrive,
  Hexagon,
  History,
  Image,
  Images,
  Layers,
  Mail,
  MessageCircle,
  MessageSquare,
  Music,
  Package,
  PackageOpen,
  Puzzle,
  ScrollText,
  Smartphone,
  Trash2,
  Video,
  type LucideIcon,
} from "lucide-react";

// Rule files name icons in kebab case; only these are bundled.
export const ICONS: Record<string, LucideIcon> = {
  "app-window": AppWindow,
  archive: Archive,
  beer: Beer,
  brain: Brain,
  clock: Clock,
  code: Code,
  compass: Compass,
  container: Container,
  database: Database,
  download: Download,
  "file-box": FileBox,
  "file-warning": FileWarning,
  "folder-cog": FolderCog,
  "folder-output": FolderOutput,
  "folder-tree": FolderTree,
  globe: Globe,
  hammer: Hammer,
  "hard-drive": HardDrive,
  hexagon: Hexagon,
  history: History,
  image: Image,
  images: Images,
  layers: Layers,
  mail: Mail,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  music: Music,
  package: Package,
  "package-open": PackageOpen,
  puzzle: Puzzle,
  "scroll-text": ScrollText,
  smartphone: Smartphone,
  trash: Trash2,
  video: Video,
};
